### ISSUE TITLE
Allow custom volume mounts to aiidalab container

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-launch#130]
I've just started playing with `aiidalab-launch` and it works great! Much better experience than before.

However, it seems that I cannot currently utilize it since I need to have a custom volume mounted for my aiidalab application.* Would it be possible to add a profile setting to have custom volumes?

* my package depends on a quantum chemistry package ORCA, which is not open source and cannot be automatically installed. My current solution to this problem is to mount a directory with the ORCA binaries as a volume to the aiidalab container. I am all ears if there is a better approach. :-)

**Comment by csadorf** [comment]
@danielhollas Thanks for the feedback and for reporting the issue! I think adding a feature for mounting additional volumes would be in scope. 

For this, I would suggest to add a a `volumes` key to the [profile configuration](https://github.com/aiidalab/aiidalab-launch/blob/64dc0004b105b2341358692f32490b8631ee69e8/aiidalab_launch/profile.py#L51-L58) that uses a syntax similar or equal to those of the docker-compose file: https://docs.docker.com/compose/compose-file/#volumes

I don't have the bandwidth to work on this at the moment, but I can propose this to the team at the next meeting. In any case, would you potentially be open/interested in giving this a shot yourself?

Please note that aiidalab-launch has some function overlap with docker-compose and there is an ongoing effort (#127) that would potentially refactor aiidalab-launch to use docker-compose instead of docker, but I don't expect that to come to pass for at least another month or so.

**Comment by danielhollas** [comment]
@csadorf Thank for the info! I will give it a shot, feel free to assign this issue to me.
