### ISSUE TITLE
Hide stack traces unless debug mode is enabled.

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-launch#135]
I always find it jarring when as a user a python CLI tool spews a full stack trace into my terminal. More importantly, I always have to squint to find tha actual error.

I wonder whether it wouldn't be a more user friendly to disable stack traces unless a debug mode is enabled? Something.like below perhaps?
https://stackoverflow.com/a/27674608

I am asking both as a user of this specific package, but also in general as a newbie Python dev about what's the best practice here.

**Comment by csadorf** [comment]
I agree, there should ideally never be a traceback visible to the user which is why all expected exceptions should be caught and handled in https://github.com/aiidalab/aiidalab-launch/blob/main/aiidalab_launch/__main__.py . 

However, it is of course possible that something "falls through the cracks", and setting the tracebacklimit to 0 could be a viable solution to address that. But I assume that the error message would potentially be even more cryptic, the traceback dump at least indicates that something went "horribly wrong". Using a custom `sys.excepthook` exception handler might be a better option, where we can at least show a message that explains that the program crashed with an unexpected error.

Maybe it would be worthwhile to find an example of such an implementation in a "popular" CLI application that we could compare against?

Did you encounter a traceback with the package or is this just a general question?

**Comment by csadorf** [comment]
@danielhollas Would you be open to trying to implement this?

**Comment by danielhollas** [comment]
@csadorf sure, I can give it a shot, feel free to assign this to me. Although it's a low priority for now so if somebody else wants to go ahead feel free.
